CREATE DATABASE ComprasNet;

-- -------------------TBL_TIPO--------------------------------
use ComprasNet;

CREATE TABLE TBL_TIPO(
ID INT(10) AUTO_INCREMENT,
ID_TIPO INT(10),
NOME VARCHAR(1000) NOT NULL,
PRIMARY KEY (ID));

INSERT INTO TBL_TIPO(ID_TIPO, NOME)
VALUES(@ID_TIPO, @NOME)
-- -------------------TBL_PODERES--------------------------------
CREATE TABLE TBL_PODERES(
ID INT(10) AUTO_INCREMENT,
ID_PODERES VARCHAR(1000),
NOME VARCHAR(1000) NOT NULL,
PRIMARY KEY (ID));

INSERT INTO TBL_PODERES(ID_PODERES, NOME) VALUES(@ID_PODERES, @NOME)
-- -------------------TBL_ESFERA--------------------------------

CREATE TABLE TBL_ESFERA(
ID INT(10) AUTO_INCREMENT,
ID_ESFERA VARCHAR(5),
NOME VARCHAR(1000) NOT NULL,
PRIMARY KEY (ID));
-- -------------------TBL_MUNICIPIO--------------------------------

CREATE TABLE TBL_MUNICIPIO(
ID INT(10) AUTO_INCREMENT,
ID_MONICIPIO INT(10),
ID_ESTADO INT(10),
NOME VARCHAR(1000) NOT NULL,
PRIMARY KEY (ID));

ALTER TABLE TBL_MUNICIPIO
ADD ID_ESTADO INT(10);
-- -------------------TBL_ESTADO-------------------------------- 

CREATE TABLE TBL_ESTADO(
ID INT(10) AUTO_INCREMENT,
UF VARCHAR(2) NOT NULL,
PRIMARY KEY (ID));
-- -------------------TBL_ANO--------------------------------

CREATE TABLE TBL_ANO(
ID INT(10) AUTO_INCREMENT,
ANO VARCHAR(6) NOT NULL,
PRIMARY KEY (ID));
-- -------------------TBL_UNIDADE--------------------------------

CREATE TABLE TBL_UNIDADE(
ID INT(10) AUTO_INCREMENT,
ID_UNIDADE INT(10),
CODIGO VARCHAR(100),
NOME VARCHAR(100) NOT NULL,
CODIGO_NOME VARCHAR(600) NOT NULL,
PRIMARY KEY (ID));

-- -------------------TBL_ORGAO--------------------------------
CREATE TABLE TBL_ORGAO(
ID INT(10) AUTO_INCREMENT,
ID_ORGAO INT(10),
CNPJ VARCHAR(18),
NOME VARCHAR(600) NOT NULL,
PRIMARY KEY (ID));
-- -------------------TBL_MODALIDADE--------------------------------
CREATE TABLE TBL_MODALIDADE(
ID INT(10) AUTO_INCREMENT,
ID_MODALIDADE INT(10),
NOME VARCHAR(1000) NOT NULL,
PRIMARY KEY (ID));
-- -------------------TBL_ITEM_CONTRATO--------------------------------


CREATE TABLE TBL_ITEM_CONTRATO(
ID INT(10) AUTO_INCREMENT,
ID_CONTRATO INT(10),
VALORTOTAL  DECIMAL(10, 2),            
DATAATUALIZACAO  datetime,       
QUANTIDADE DECIMAL(10, 2),            
DATAINCLUSAO datetime,           
NUMEROITEM INT(10),             
DESCRICAO  VARCHAR(6000),            
MATERIALOUSERVICO VARCHAR(6000),      
TIPOBENEFICIO INT(10),            
UNIDADEMEDIDA VARCHAR(1000),           
VALORUNITARIOESTIMADO DECIMAL(10, 2),
SITUACAOCOMPRAITEM  INT(10),    
MATERIALOUSERVICONOME VARCHAR(1000),  
SITUACAOCOMPRAITEMNOME VARCHAR(200), 
TIPOBENEFICIONOME VARCHAR(1000),      
CRITERIOJULGAMENTOID INT(10),  
CRITERIOJULGAMENTONOME  VARCHAR(1000),
FOREIGN KEY (ID_CONTRATO) REFERENCES TBL_CONTRATO(ID),
PRIMARY KEY (ID));

-- -------------------TBL_CONTRATO--------------------------------
SELECT * FROM TBL_CONTRATO 



CREATE TABLE TBL_CONTRATO(
ID INT(10) AUTO_INCREMENT,
ID_CONTRATO VARCHAR(100),
TITLE VARCHAR(1000) NOT NULL,
DESCRIPTION VARCHAR(8000) NOT NULL,
ANO INT(10),
ID_ORGAO INT(10),
ID_UNIDADE INT(10),
ID_ESFERA INT(10),
ID_PODER INT(10),
ID_MUNICIPIO INT(10),
ID_ESTADO INT(10),
ID_MODALIDADE INT(10),
DATA_PUBLICACAO_PNCP datetime,
DATA_ATUALIZACAO_PNCP datetime,
DATA_ASSINATURA datetime,
DATA_INICIO_VIGENCIA datetime,
DATA_FIM_VIGENCIA datetime,
VALOR_GLOBAL  DECIMAL(10, 2),
ID_TIPO INT(10),
FLG_ATIVO boolean default FALSE,
FOREIGN KEY (ID_ORGAO) REFERENCES TBL_ORGAO(ID),
FOREIGN KEY (ID_UNIDADE) REFERENCES TBL_UNIDADE(ID),
FOREIGN KEY (ID_ESFERA) REFERENCES TBL_ESFERA(ID),
FOREIGN KEY (ID_PODER) REFERENCES TBL_PODERES(ID),
FOREIGN KEY (ID_MUNICIPIO) REFERENCES TBL_MUNICIPIO(ID),
FOREIGN KEY (ID_ESTADO) REFERENCES TBL_ESTADO(ID),
FOREIGN KEY (ID_MODALIDADE) REFERENCES TBL_MODALIDADE(ID),
FOREIGN KEY (ID_TIPO) REFERENCES TBL_TIPO(ID),
PRIMARY KEY (ID));

SELECT * FROM TBL_CONTRATO;
-- -------------------TBL_MEUS_NEGOCIOS--------------------------------
CREATE TABLE TBL_MEUS_NEGOCIOS(
ID INT(10) AUTO_INCREMENT,
ID_USUARIO INT(10),
ID_CONTRATO INT(10),
ID_ITEM INT(10),
FLG_STATUS INT(1),
FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO(CD_ID),
PRIMARY KEY (ID));

-- -------------------TBL_FORNECEDORES--------------------------------
CREATE TABLE TBL_FORNECEDOR(
ID INT(10) AUTO_INCREMENT,
ID_CONTATO INT(10),
ID_USUARIO INT(10),
EMPRESA VARCHAR(150),
CNPJ VARCHAR(150),
NOME_CONTATO_COMERCIAL varchar(150),
MODELO varchar(150),
MARCA varchar(150),
DESCRICAO_PRODUTO varchar(3000),
VALOR DECIMAL(10, 2),
DATA_CADASTRO datetime,
FLG_ATIVO BOOLEAN,
FOREIGN KEY (ID_CONTATO) REFERENCES TBL_CONTATO(CD_ID),
FOREIGN KEY (ID_USUARIO) REFERENCES TBL_USUARIO(CD_ID),
PRIMARY KEY (ID));

-- -------------------TBL_FORNECEDORES_VINCULO_ITEM_CONTRATO--------------------------------
CREATE TABLE TBL_FORNECEDOR_VINCULO_ITEM_CONTRATO(
ID INT(10) AUTO_INCREMENT,
ID_CONTRATO INT(10),
ID_ITEM INT(10),
ID_FORNECEDOR INT(10),
DATA_CADASTRO datetime,
FOREIGN KEY (ID_CONTRATO) REFERENCES TBL_CONTRATO(ID),
FOREIGN KEY (ID_ITEM) REFERENCES TBL_ITEM_CONTRATO(ID),
FOREIGN KEY (ID_FORNECEDOR) REFERENCES TBL_FORNECEDOR(ID),
PRIMARY KEY (ID));

-- VERIFICAR SE VINCULO EXISTE
SELECT A.ID FROM TBL_FORNECEDOR_VINCULO_ITEM_CONTRATO AS A
INNER JOIN TBL_MEUS_NEGOCIOS AS B ON A.ID_ITEM = B.ID_ITEM
WHERE  B.ID_USUARIO = @ID_USUARIO
AND A.ID_CONTRATO = @ID_CONTRATO AND A.ID_ITEM = @ID_ITEM

-- OBTER ITENS E FORNECEDOR
SELECT  C.ID AS ID_FORNECEDOR,
  D.ID AS ID_ITEM, D.ID_CONTRATO 
, D.VALORTOTAL, D.DATAATUALIZACAO, D.QUANTIDADE             
, D.DATAINCLUSAO, D.NUMEROITEM , D.DESCRICAO            
, D.MATERIALOUSERVICO, D.TIPOBENEFICIO            
, D.UNIDADEMEDIDA, D.VALORUNITARIOESTIMADO, D.SITUACAOCOMPRAITEM     
, D.MATERIALOUSERVICONOME, D.SITUACAOCOMPRAITEMNOME 
, D.TIPOBENEFICIONOME, D.CRITERIOJULGAMENTOID ,D.CRITERIOJULGAMENTONOME 
, C.ID AS ID_FORNECEDOR, C.EMPRESA, C.CNPJ
, C.NOME_CONTATO_COMERCIAL, C.MODELO, C.MARCA, C.DESCRICAO_PRODUTO
, C.VALOR, E.DES_EMAIL, E.DES_NUM_TELEFONE, B.ID AS ID_VINCULO
 FROM TBL_MEUS_NEGOCIOS AS A
LEFT  JOIN TBL_FORNECEDOR_VINCULO_ITEM_CONTRATO AS B ON A.ID_ITEM = B.ID_ITEM
LEFT  JOIN TBL_FORNECEDOR AS C ON B.ID_FORNECEDOR = C.ID
LEFT  JOIN TBL_ITEM_CONTRATO AS D ON A.ID_ITEM = D.ID
LEFT  JOIN TBL_CONTATO AS E ON C.ID_CONTATO = E.CD_ID
WHERE A.ID_USUARIO = 24  AND A.ID_CONTRATO = 24871