use ComprasNet;

CREATE TABLE TBL_CONTATO(
CD_ID INT(20) AUTO_INCREMENT,
DES_EMAIL VARCHAR(200) NOT NULL,
DES_NUM_TELEFONE VARCHAR(15) NOT NULL,
DT_CADASTRO DATE  NULL,
PRIMARY KEY (CD_ID));

CREATE TABLE TBL_LOGIN(
CD_ID INT(100) AUTO_INCREMENT,
DES_NOME_USUARIO VARCHAR(200) NOT NULL,
DES_SENHA VARCHAR(50) NOT NULL,
DT_CADASTRO DATE  NULL,
PRIMARY KEY (CD_ID));

CREATE TABLE TBL_RESET_PASSWORD(
CD_ID INT(100) AUTO_INCREMENT,
CD_LOGIN INT(100),
FLG_ATIVO BOOLEAN  DEFAULT TRUE,
DT_CADASTRO DATE  NULL,
FOREIGN KEY (CD_LOGIN) REFERENCES TBL_LOGIN(CD_ID),
PRIMARY KEY (CD_ID));


CREATE TABLE TBL_PERFIL(
CD_ID INT(100) AUTO_INCREMENT,
DES_PERFIL VARCHAR(20),
DES_DESCRICAO VARCHAR(300),
DT_CADASTRO DATETIME,
PRIMARY KEY (CD_ID));


CREATE TABLE TBL_USUARIO(
CD_ID INT(100) AUTO_INCREMENT,
DES_NOME VARCHAR(500) NOT NULL,
DES_CPFCNPJ VARCHAR(20) NOT NULL,
FLG_ATIVO BOOLEAN  DEFAULT false,
CD_CONTATO_ID INT(100),
CD_LOGIN_ID INT(100),
CD_PERFIL_ID INT(100),
DT_CADASTRO DATE  NULL,
FOREIGN KEY (CD_CONTATO_ID) REFERENCES TBL_CONTATO(CD_ID),
FOREIGN KEY (CD_LOGIN_ID) REFERENCES TBL_LOGIN(CD_ID),
FOREIGN KEY (CD_PERFIL_ID) REFERENCES TBL_PERFIL(CD_ID),
PRIMARY KEY (CD_ID));

CREATE TABLE TBL_PARAMETRO(
CD_ID INT(100) AUTO_INCREMENT,
DES_VALUE VARCHAR(8000),
DES_IDENTIFICADOR VARCHAR(50),
DES_DESCRICAO VARCHAR(300),
DT_CADASTRO DATETIME,
PRIMARY KEY (CD_ID));

SELECT * FROM TBL_PARAMETRO WHERE DES_IDENTIFICADOR = 'CORPO_EMAIL_CADASTRO'

use ComprasNet;
delete FROM TBL_USUARIO where CD_ID >0;
delete FROM TBL_LOGIN  where CD_ID >0;
delete FROM TBL_CONTATO  where CD_ID >0;





